### PR TITLE
Fix met station table in met data tutorial

### PR DESCRIPTION
**Pull request by KristinaRiemer**
Update met tutorial as described in #176.

### CODE REVIEW

**Comment by KristinaRiemer** [comment]
@dlebauer, Max said this looks good, would you be able to review it so that it can be merged?

**Comment by dlebauer** [comment]
* Should there be html and js checked into this PR? 
* I think that the line `| 3212        | UA-MAC AZMET Weather Station - irrigation     |` should also be updated - it is just the Field Scanner irrigation station.
* have these names been updated in the geostreams metadata as well?

**Comment by KristinaRiemer** [comment]
@dlebauer I thought committing all those files seemed weird, and you're right, I just needed to include source files. I fixed that, including the irrigation station name. 

I'm not sure if metadata has changed correctly? The stream name now doesn't include AZMET, but the sensor name does. Is that right? 

https://terraref.ncsa.illinois.edu/clowder/api/geostreams/sensors/438/streams
Screen Shot 2019-10-22 at 7 38 27 AM

https://terraref.ncsa.illinois.edu/clowder/api/geostreams/datapoints?stream_id=46431&since=2017-01-02&until=2017-01-31
Screen Shot 2019-10-22 at 7 39 26 AM

**Comment by KristinaRiemer** [comment]
@max-zilla, if you look at the second screenshot in my previous comment, it looks like the sensor is still called AZMET. @dlebauer I'm not sure what that should be renamed?

**Comment by max-zilla** [comment]
It looks like I updated the streams but missed the sensor - let me take a quick look at fixing that in the database.

**Comment by max-zilla** [comment]
OK, I updated https://terraref.ncsa.illinois.edu/clowder/api/geostreams/sensors/438 so it reads ```UA-MAC Field Scanner Weather Station```... this fixes sensor_name in all the datapoints.

**Comment by KristinaRiemer** [comment]
This looks good to me. @dlebauer?

**Pull request merged**
