### PR TITLE
Automate download and read in of sensor files

### PR DESCRIPTION
**Pull request by KristinaRiemer**
The only tricky part about using this method to download the files from Google Drive is that it requires logging into Google the first time. I'm happy to not do this if it seems like too much.

### CODE REVIEW

**Comment by dlebauer** [comment]
We should be able to add these to the public sample data in clowder.

_____________________
David LeBauer, PhD
Director of Data Science for the Arizona Experiment Station
1230 N Cherry Avenue, Tucson, Arizona 85721
207 BSRL
University of Arizona
520-621-4381
dlebauer@email.arizona.edu

________________________________

**Comment by KristinaRiemer** [comment]
Okay, good. Downloading from Google Drive URLs is apparently not trivial.

**Comment by Chris-Schnaufer** [comment]
David to find the Clowder location and document that here.

**Comment by dlebauer** [comment]
They are here now https://terraref.ncsa.illinois.edu/clowder/datasets/5c81709a4f0c78f6486d686c

**Comment by KristinaRiemer** [comment]
Changed downloading from Google Drive zip to Clowder zip.

**Comment by KristinaRiemer** [comment]
Great! Merging this then.

**Pull request merged**
