### PR TITLE
Attempt to update my master with upstream master

### PR DESCRIPTION
**Pull request by KristinaRiemer**
GitHub is telling me that my fork's master branch has commits that the main repo's master doesn't have, even though those commits are in the main repo? https://github.com/terraref/tutorials/commit/9a75cd9abb98fd993c0f954b18fc0c3238d88d09

I'm not sure if this PR will fix that or not. 😕

### CODE REVIEW

**Comment by dlebauer** [comment]
There are no changes to the files so I'm not sure if we need to merge this https://github.com/terraref/tutorials/pull/158/files

Maybe close this and `git reset --hard HEAD` to reset master on your clone? https://stackoverflow.com/a/12049323

**Comment by KristinaRiemer** [comment]
I did that and pushed to my fork, but it didn't change anything. I think my HEAD is in the right place, because those commits are older than the most recent one.

**Comment by dlebauer** [comment]
maybe you need

```
git fetch --all
git reset --hard origin/master
```

optionally add https://stackoverflow.com/a/5361169/513006

```
git clean -n -f -d # dry run to see what happens
git clean -f -d
git pull
```

???

**Comment by KristinaRiemer** [comment]
I did the following: 
```
git reset --hard upstream/master
git push --force origin master
```
This came from this [SO post](https://stackoverflow.com/a/29049698). This apparently automatically closed this PR. My fork master is now in line with the main repo master.

**Pull request closed without merging**
